package com.inge.edecisiones;

import java.io.InputStream;
import java.util.Date;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Notification;
import com.vaadin.ui.OptionGroup;
import com.vaadin.ui.Panel;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Upload;
import com.vaadin.ui.VerticalLayout;

public class VEditarUsuario extends CustomComponent implements View{

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_5;
	@AutoGenerated
	private Panel panel_Imagen;
	@AutoGenerated
	private VerticalLayout verticalLayout_3;
	@AutoGenerated
	private Label label_1;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_6;
	@AutoGenerated
	private Button btn_Volver;
	@AutoGenerated
	private Button btn_Guardar;
	@AutoGenerated
	private Upload upl_Imagen;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_11;
	@AutoGenerated
	private PopupDateField dtf_Fecha;
	@AutoGenerated
	private Label lbl_fecha;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private OptionGroup opg_Sexo;
	@AutoGenerated
	private Label label_2;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_9;
	@AutoGenerated
	private TextField txt_Apellido2;
	@AutoGenerated
	private Label lbl_apellido2;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_8;
	@AutoGenerated
	private TextField txt_Apellido1;
	@AutoGenerated
	private Label lbl_apellido1;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_7;
	@AutoGenerated
	private TextField txt_Nombre;
	@AutoGenerated
	private Label lbl_nombre;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_4;
	@AutoGenerated
	private TextField txtCedula;
	@AutoGenerated
	private Label lbl_Cedula;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_10;
	@AutoGenerated
	private PasswordField psw_password2;
	@AutoGenerated
	private Label label_3;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_2;
	@AutoGenerated
	private PasswordField psw_Password;
	@AutoGenerated
	private Label lblPass;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_3;
	@AutoGenerated
	private TextField txt_email;
	@AutoGenerated
	private Label lbl_Email;
	@AutoGenerated
	private Panel panel_Menu;
	@AutoGenerated
	private VerticalLayout verticalLayout_2;
	//atributos propios
	private Usuario usuario;
	private ControlUsuario controlador;
	private InputStream foto;
	private Menu menu;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public VEditarUsuario(final ControlUsuario controlador) {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		this.controlador = controlador;
		foto = null;
		
		//menu = new Menu(controlador.getEdecisiones());
		panel_Menu.setContent(new Menu(controlador.getEdecisiones()));
		panel_Menu.setSizeUndefined();
		// TODO add user code here
		opg_Sexo.addItem("Masculino");
		opg_Sexo.addItem("Femenino");
		opg_Sexo.setValue("Masculino");
		
		//añadir listeners a los botones
		btn_Guardar.addClickListener(new Button.ClickListener() {
			
			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				if(!tieneCamposVacios()){
					if(txtCedula.getValue().length()!=9||txtCedula.getValue().charAt(0)=='0'){
						Notification.show("Cédula invalida");
					}
					else if(!psw_Password.getValue().equals(psw_password2.getValue())){
						Notification.show("Las contraseñas no coinciden");
					}
					else{
						int cedula = Integer.parseInt(txtCedula.getValue());
						Ciudadano c = new Ciudadano(txt_Nombre.getValue(), txt_Apellido1.getValue(), 
								txt_Apellido2.getValue(), cedula);
						boolean sexo = (opg_Sexo.getValue().toString().equalsIgnoreCase("Femenino"))? true:false;
						c.SetSexo(sexo);
						c.SetFechaNac(dtf_Fecha.getValue());
						usuario.setDatosCiudadano(c);
						usuario.SetContrasena(psw_Password.getValue());
						usuario.SetEmail(txt_email.getValue());
						usuario.SetFoto(foto);
						controlador.validar(usuario);
					}
				}
			}
		});
		
		btn_Volver.addClickListener(new Button.ClickListener() {
			
			@Override
			public void buttonClick(ClickEvent event) {
				if ( controlador.getEdecisiones().usuarioLogin() ) {
					controlador.ir_a_panel();			
				}
				else {
					controlador.ir_a_login();
				}
			}
		});
	}
	
	//Carga los datos del usuario -> en caso de editar
	public void cargarDatos( ){
		Ciudadano c = usuario.getDatosCiudadano();
		txt_email.setValue(usuario.GetEmail());
		psw_Password.setValue(usuario.GetPassword());
		psw_password2.setValue(usuario.GetPassword());
		String[] nombre = c.GetName().split(" ");
		txt_Nombre.setValue(nombre[0]);
		txt_Apellido1.setValue(nombre[1]);
		txt_Apellido2.setValue(nombre[2]);
		txtCedula.setValue(Integer.toString(c.GetCedula()));
		txtCedula.setEnabled(false);
		if(c.GetSexo()){
			opg_Sexo.setValue("Femenino");
		}
		else{
			opg_Sexo.setValue("Masculino");
		}
		dtf_Fecha.setValue(c.GetFechaNac());
	}
	
	//limpia los campos de la interfaz
	public void limpiarDatos(){
		txt_Nombre.setValue("");
		txt_email.setValue("");
		psw_Password.setValue("");
		psw_password2.setValue("");
		txt_Apellido1.setValue("");
		txt_Apellido2.setValue("");
		txtCedula.setValue("");
		txtCedula.setEnabled(true);
		dtf_Fecha.setValue(new Date());
	}
	
	public void setUsuario(Usuario usuario){
		this.usuario = usuario;
	}
	
	public boolean tieneCamposVacios() {
		boolean algunvacio = false;
		
		algunvacio = txt_email.getValue().isEmpty();
		algunvacio = (algunvacio | psw_Password.getValue().isEmpty());
		algunvacio = (algunvacio | psw_password2.getValue().isEmpty());
		algunvacio = (algunvacio | txtCedula.getValue().isEmpty());
		algunvacio = (algunvacio | txt_Nombre.getValue().isEmpty());
		algunvacio = (algunvacio | txt_Apellido1.getValue().isEmpty());
		algunvacio = (algunvacio | txt_Apellido2.getValue().isEmpty());
		
		return algunvacio;
	}
	
	@Override
	public void enter(ViewChangeEvent event) {
		// TODO Auto-generated method stub
		
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// panel_Menu
		panel_Menu = buildPanel_Menu();
		mainLayout.addComponent(panel_Menu);
		
		// horizontalLayout_3
		horizontalLayout_3 = buildHorizontalLayout_3();
		mainLayout.addComponent(horizontalLayout_3);
		
		// horizontalLayout_2
		horizontalLayout_2 = buildHorizontalLayout_2();
		mainLayout.addComponent(horizontalLayout_2);
		
		// horizontalLayout_10
		horizontalLayout_10 = buildHorizontalLayout_10();
		mainLayout.addComponent(horizontalLayout_10);
		
		// horizontalLayout_4
		horizontalLayout_4 = buildHorizontalLayout_4();
		mainLayout.addComponent(horizontalLayout_4);
		
		// horizontalLayout_7
		horizontalLayout_7 = buildHorizontalLayout_7();
		mainLayout.addComponent(horizontalLayout_7);
		
		// horizontalLayout_8
		horizontalLayout_8 = buildHorizontalLayout_8();
		mainLayout.addComponent(horizontalLayout_8);
		
		// horizontalLayout_9
		horizontalLayout_9 = buildHorizontalLayout_9();
		mainLayout.addComponent(horizontalLayout_9);
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		mainLayout.addComponent(horizontalLayout_1);
		
		// horizontalLayout_11
		horizontalLayout_11 = buildHorizontalLayout_11();
		mainLayout.addComponent(horizontalLayout_11);
		
		// upl_Imagen
		upl_Imagen = new Upload();
		upl_Imagen.setCaption("Seleccionar archivo de imagen:");
		upl_Imagen.setImmediate(false);
		upl_Imagen.setWidth("-1px");
		upl_Imagen.setHeight("-1px");
		mainLayout.addComponent(upl_Imagen);
		
		// horizontalLayout_6
		horizontalLayout_6 = buildHorizontalLayout_6();
		mainLayout.addComponent(horizontalLayout_6);
		
		// horizontalLayout_5
		horizontalLayout_5 = buildHorizontalLayout_5();
		mainLayout.addComponent(horizontalLayout_5);
		
		return mainLayout;
	}

	@AutoGenerated
	private Panel buildPanel_Menu() {
		// common part: create layout
		panel_Menu = new Panel();
		panel_Menu.setImmediate(false);
		panel_Menu.setWidth("100px");
		panel_Menu.setHeight("30px");
		
		// verticalLayout_2
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setImmediate(false);
		verticalLayout_2.setWidth("100.0%");
		verticalLayout_2.setHeight("100.0%");
		verticalLayout_2.setMargin(false);
		panel_Menu.setContent(verticalLayout_2);
		
		return panel_Menu;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_3() {
		// common part: create layout
		horizontalLayout_3 = new HorizontalLayout();
		horizontalLayout_3.setImmediate(false);
		horizontalLayout_3.setWidth("-1px");
		horizontalLayout_3.setHeight("-1px");
		horizontalLayout_3.setMargin(false);
		
		// lbl_Email
		lbl_Email = new Label();
		lbl_Email.setImmediate(false);
		lbl_Email.setWidth("-1px");
		lbl_Email.setHeight("-1px");
		lbl_Email.setValue("Correo Electónico(*):");
		horizontalLayout_3.addComponent(lbl_Email);
		
		// txt_email
		txt_email = new TextField();
		txt_email.setImmediate(false);
		txt_email.setWidth("-1px");
		txt_email.setHeight("-1px");
		horizontalLayout_3.addComponent(txt_email);
		
		return horizontalLayout_3;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_2() {
		// common part: create layout
		horizontalLayout_2 = new HorizontalLayout();
		horizontalLayout_2.setImmediate(false);
		horizontalLayout_2.setWidth("-1px");
		horizontalLayout_2.setHeight("-1px");
		horizontalLayout_2.setMargin(false);
		
		// lblPass
		lblPass = new Label();
		lblPass.setImmediate(false);
		lblPass.setWidth("-1px");
		lblPass.setHeight("-1px");
		lblPass.setValue("Contraseña(*):");
		horizontalLayout_2.addComponent(lblPass);
		
		// psw_Password
		psw_Password = new PasswordField();
		psw_Password.setImmediate(false);
		psw_Password.setWidth("-1px");
		psw_Password.setHeight("-1px");
		horizontalLayout_2.addComponent(psw_Password);
		
		return horizontalLayout_2;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_10() {
		// common part: create layout
		horizontalLayout_10 = new HorizontalLayout();
		horizontalLayout_10.setImmediate(false);
		horizontalLayout_10.setWidth("-1px");
		horizontalLayout_10.setHeight("-1px");
		horizontalLayout_10.setMargin(false);
		
		// label_3
		label_3 = new Label();
		label_3.setImmediate(false);
		label_3.setWidth("-1px");
		label_3.setHeight("-1px");
		label_3.setValue("Contraseña:");
		horizontalLayout_10.addComponent(label_3);
		
		// psw_password2
		psw_password2 = new PasswordField();
		psw_password2.setImmediate(false);
		psw_password2.setWidth("-1px");
		psw_password2.setHeight("-1px");
		horizontalLayout_10.addComponent(psw_password2);
		
		return horizontalLayout_10;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_4() {
		// common part: create layout
		horizontalLayout_4 = new HorizontalLayout();
		horizontalLayout_4.setImmediate(false);
		horizontalLayout_4.setWidth("-1px");
		horizontalLayout_4.setHeight("-1px");
		horizontalLayout_4.setMargin(false);
		
		// lbl_Cedula
		lbl_Cedula = new Label();
		lbl_Cedula.setImmediate(false);
		lbl_Cedula.setWidth("-1px");
		lbl_Cedula.setHeight("-1px");
		lbl_Cedula.setValue("Cédula(*):");
		horizontalLayout_4.addComponent(lbl_Cedula);
		
		// txtCedula
		txtCedula = new TextField();
		txtCedula.setImmediate(false);
		txtCedula.setWidth("-1px");
		txtCedula.setHeight("-1px");
		horizontalLayout_4.addComponent(txtCedula);
		
		return horizontalLayout_4;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_7() {
		// common part: create layout
		horizontalLayout_7 = new HorizontalLayout();
		horizontalLayout_7.setImmediate(false);
		horizontalLayout_7.setWidth("-1px");
		horizontalLayout_7.setHeight("-1px");
		horizontalLayout_7.setMargin(false);
		
		// lbl_nombre
		lbl_nombre = new Label();
		lbl_nombre.setImmediate(false);
		lbl_nombre.setWidth("-1px");
		lbl_nombre.setHeight("-1px");
		lbl_nombre.setValue("Nombre(*):");
		horizontalLayout_7.addComponent(lbl_nombre);
		
		// txt_Nombre
		txt_Nombre = new TextField();
		txt_Nombre.setImmediate(false);
		txt_Nombre.setWidth("-1px");
		txt_Nombre.setHeight("-1px");
		horizontalLayout_7.addComponent(txt_Nombre);
		
		return horizontalLayout_7;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_8() {
		// common part: create layout
		horizontalLayout_8 = new HorizontalLayout();
		horizontalLayout_8.setImmediate(false);
		horizontalLayout_8.setWidth("-1px");
		horizontalLayout_8.setHeight("-1px");
		horizontalLayout_8.setMargin(false);
		
		// lbl_apellido1
		lbl_apellido1 = new Label();
		lbl_apellido1.setImmediate(false);
		lbl_apellido1.setWidth("-1px");
		lbl_apellido1.setHeight("-1px");
		lbl_apellido1.setValue("Apellido1(*):");
		horizontalLayout_8.addComponent(lbl_apellido1);
		
		// txt_Apellido1
		txt_Apellido1 = new TextField();
		txt_Apellido1.setImmediate(false);
		txt_Apellido1.setWidth("-1px");
		txt_Apellido1.setHeight("-1px");
		horizontalLayout_8.addComponent(txt_Apellido1);
		
		return horizontalLayout_8;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_9() {
		// common part: create layout
		horizontalLayout_9 = new HorizontalLayout();
		horizontalLayout_9.setImmediate(false);
		horizontalLayout_9.setWidth("-1px");
		horizontalLayout_9.setHeight("-1px");
		horizontalLayout_9.setMargin(false);
		
		// lbl_apellido2
		lbl_apellido2 = new Label();
		lbl_apellido2.setImmediate(false);
		lbl_apellido2.setWidth("-1px");
		lbl_apellido2.setHeight("-1px");
		lbl_apellido2.setValue("Apellido2(*):");
		horizontalLayout_9.addComponent(lbl_apellido2);
		
		// txt_Apellido2
		txt_Apellido2 = new TextField();
		txt_Apellido2.setImmediate(false);
		txt_Apellido2.setWidth("-1px");
		txt_Apellido2.setHeight("-1px");
		horizontalLayout_9.addComponent(txt_Apellido2);
		
		return horizontalLayout_9;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("-1px");
		horizontalLayout_1.setHeight("-1px");
		horizontalLayout_1.setMargin(false);
		
		// label_2
		label_2 = new Label();
		label_2.setImmediate(false);
		label_2.setWidth("-1px");
		label_2.setHeight("-1px");
		label_2.setValue("Sexo(*):");
		horizontalLayout_1.addComponent(label_2);
		
		// opg_Sexo
		opg_Sexo = new OptionGroup();
		opg_Sexo.setImmediate(false);
		opg_Sexo.setWidth("-1px");
		opg_Sexo.setHeight("-1px");
		horizontalLayout_1.addComponent(opg_Sexo);
		
		return horizontalLayout_1;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_11() {
		// common part: create layout
		horizontalLayout_11 = new HorizontalLayout();
		horizontalLayout_11.setImmediate(false);
		horizontalLayout_11.setWidth("-1px");
		horizontalLayout_11.setHeight("-1px");
		horizontalLayout_11.setMargin(false);
		
		// lbl_fecha
		lbl_fecha = new Label();
		lbl_fecha.setImmediate(false);
		lbl_fecha.setWidth("-1px");
		lbl_fecha.setHeight("-1px");
		lbl_fecha.setValue("Fecha de nacimiento(*):");
		horizontalLayout_11.addComponent(lbl_fecha);
		
		// dtf_Fecha
		dtf_Fecha = new PopupDateField();
		dtf_Fecha.setImmediate(false);
		dtf_Fecha.setWidth("-1px");
		dtf_Fecha.setHeight("-1px");
		horizontalLayout_11.addComponent(dtf_Fecha);
		
		return horizontalLayout_11;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_6() {
		// common part: create layout
		horizontalLayout_6 = new HorizontalLayout();
		horizontalLayout_6.setImmediate(false);
		horizontalLayout_6.setWidth("-1px");
		horizontalLayout_6.setHeight("-1px");
		horizontalLayout_6.setMargin(false);
		
		// btn_Guardar
		btn_Guardar = new Button();
		btn_Guardar.setCaption("Guardar");
		btn_Guardar.setImmediate(true);
		btn_Guardar.setWidth("-1px");
		btn_Guardar.setHeight("-1px");
		horizontalLayout_6.addComponent(btn_Guardar);
		
		// btn_Volver
		btn_Volver = new Button();
		btn_Volver.setCaption("Volver");
		btn_Volver.setImmediate(true);
		btn_Volver.setWidth("-1px");
		btn_Volver.setHeight("-1px");
		horizontalLayout_6.addComponent(btn_Volver);
		
		return horizontalLayout_6;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_5() {
		// common part: create layout
		horizontalLayout_5 = new HorizontalLayout();
		horizontalLayout_5.setImmediate(false);
		horizontalLayout_5.setWidth("-1px");
		horizontalLayout_5.setHeight("300px");
		horizontalLayout_5.setMargin(false);
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("-1px");
		label_1.setValue("Imagen:");
		horizontalLayout_5.addComponent(label_1);
		
		// panel_Imagen
		panel_Imagen = buildPanel_Imagen();
		horizontalLayout_5.addComponent(panel_Imagen);
		
		return horizontalLayout_5;
	}

	@AutoGenerated
	private Panel buildPanel_Imagen() {
		// common part: create layout
		panel_Imagen = new Panel();
		panel_Imagen.setImmediate(false);
		panel_Imagen.setWidth("100px");
		panel_Imagen.setHeight("30px");
		
		// verticalLayout_3
		verticalLayout_3 = new VerticalLayout();
		verticalLayout_3.setImmediate(false);
		verticalLayout_3.setWidth("200px");
		verticalLayout_3.setHeight("200px");
		verticalLayout_3.setMargin(false);
		panel_Imagen.setContent(verticalLayout_3);
		
		return panel_Imagen;
	}

}
